# Generated by Django 6.0.1 on 2026-01-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_noflyzone_drone_last_payload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'permissions': [('mark_safe', 'Can mark drone as safe')]},
        ),
    ]
