# Generated by Django 6.0.1 on 2026-01-13 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dronetelemetrypoint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noflyzone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
