# Generated by Django 6.0.1 on 2026-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_alter_drone_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dronetelemetrypoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noflyzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
