# Generated by Django 6.0.1 on 2026-01-14 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_alter_drone_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noflyzone',
            name='polygon',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noflyzone',
            name='shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], default='circle', max_length=16),
        ),
        migrations.AlterField(
            model_name='noflyzone',
            name='center_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noflyzone',
            name='center_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noflyzone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noflyzone',
            name='radius_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
